#Drone CI File!
#Commit Message: Drone! Captain Canary is here! 

kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: golang:1.12
  commands:
  - go build
  - go test


- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: paweltomasikk/test
    auto_tag: true
    auto_tag_suffix: drone-build
