kind: pipeline
name: default

steps:
  - name: build
    image: docker
    commands:
      - docker build -t myapp .

  - name: test
    image: docker
    commands:
      - docker run myapp npm test

  - name: deploy
    image: docker
    commands:
      - docker push myapp
